<?php

use Illuminate\Database\Seeder;

class LocationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('locations')->insert([

        ['city_id'=>1, 'location'=> "Aabpara Coop Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Aashiana Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Abbot Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Abdalians Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Abdul Sattar Edhi Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Abid Market",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Agrics Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ahmad Avenue",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Air Avenue",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Airline Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Airport Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Aitchison Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al Ameen Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al Faisal Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al Hafeez Gardens",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al Hamad Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al Hamra Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al Jalil Garden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al Jannat Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al Kareem Garden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al Madina Avenue",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al Noor Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al Raheem Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al Rahim Homes",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al Rehman Garden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al-Falah Cooperative Housing",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al-Hafiz Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al-Hamd Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Al-Raheem Garden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Alfalah Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ali Alam Garden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ali Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ali View Garden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ali View Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Allama Iqbal Intl Airport",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Allama Iqbal Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Allama Iqbal Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Alpha Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Altaf Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ameen Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Aashiana Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ameer-ud-Din Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Anarkali(",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Angoori Bagh",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Architects Engineers Housing",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Army Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ashiana-e-Quaid Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ashraf Garden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Asif Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Asif Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Asim Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Askari",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Atta Bakhsh Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Audit & Accounts Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Awan Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Awan-e-Tijarat Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Awasia Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "AWT Army Welfare Trust",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Azam Gardens",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Badami Bagh",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bagarian",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Baghbanpura",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bahadurabad",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bahar Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bahawalpur Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bahria Education & Medical City",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bahria Nasheman",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bahria Orchard",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bahria Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bait-ul-Raza Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bankers Avenue",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bankers Co-operative Housing",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Batapur",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Beacon House Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Beadon Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bedian Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bhagatpura",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bhatta Chowk",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bhatti Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bilal Gunj",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Birdwood Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bismillah Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "BOR Board of Revenue Housing",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Brandreth Road?",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Bund Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Canal Bank Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Canal Burg",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Canal Fort II",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Canal Garden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Canal View",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Canalberg Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Cantt",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Cantt View Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Cavalry Ground",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Central Park Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Chah Miran",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Chaman Par",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Chauburji Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Chaudhary Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "China Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Chinar Bagh",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Chungi Amar Sadhu",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Civil Defence",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Clifton Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "College Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Crescent Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Cricketer Villas",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Daroghewala",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Davis Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Defence Fort",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Defence Garden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Defence Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "DHA 11 Rahbar",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "DHA City",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "DHA Defence",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Dharampura",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Dilkusha Gardens",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Divine Gardens",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Doctors Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Dogech",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Dream Avenue Lahore",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Dream Gardens",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Dubai Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Dubban Pura",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Eden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Eden Avenue Extension",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Eden Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Eden Place Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Eden Villas",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Education Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Elite Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "EME Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "|Empress Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Excise & Taxation Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Expo Avenue Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Faisal Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Fane Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Farooq Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Fateh Garh",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Fazaia Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ferozepur Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Formanites Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gajju Matah(?",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Garden Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Garhi Shahu",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Garrison Homes",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gawalmandi",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ghalib Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ghausia Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ghaziabad",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ghous Garden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "GOR",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gosha-e-Ahbab",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Government Employees",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Government Transport",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Govt Officers Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Grand Avenues Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Green Acres Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Green Cap Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Green City",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Green Fort",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Green Park Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Green Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "GT Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gujjar Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gujjarpura",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gul-e-Damin",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gulbahar Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gulbahar Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gulberg",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Guldasht Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gulfishan Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gulshan Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gulshan Farooq Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gulshan View Residence Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gulshan-e-Ahbab",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gulshan-e-Lahore",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gulshan-e-Ravi",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Gulzar Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Habib Homes",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Haji Park Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Hajvery Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Hall Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Hamza Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Harbanspura",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Harbanspura Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Harbanspura Mor",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Hassan Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "HBFC Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Heaven Homes",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Highcourt Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Hudiara",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "IBL Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ichhra",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Icon Valley",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "IEP Engineers Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Immad Garden Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Iqbal Avenue",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Iqbal Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Iqbal Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Irum Garden Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Islamabad Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Islamia Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Islampura",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ittehad Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ittifaq Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Izmir Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Jaffar Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "affaria Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Jail Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Jalal Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Jallo",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Jamil Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Jewa Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Johar Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Jora Pull",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Jubilee Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Judicial Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Kacha Jail Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Kahna",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Kahna Kacha",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Kamahan Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Karbath",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Karim Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Khayaban-e-Amin",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Khayaban-e-Jinnah Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Khayaban-e-Zohra(?",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Kot Khawaja Saeed",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Kot Lakhpat",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Kotli Abdur Rahman",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Krishan Nagar",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Lahore Avenue",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Lahore Canal Bank Cooperative",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Lahore Cantt Coop Housing",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Lahore Garden Housing Scheme(?",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Lahore Medical Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Lahore Motorway City",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Lahore Press Club Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Lake City",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Lakhodher",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Lalazaar Garden(?",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Lalazar",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "LDA Avenue",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Lower Mall",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Lytton Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Madina Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Madina Homes",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Main Canal Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Makkah Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Malik Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mall Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Manawan",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Manga - Raiwind Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Manga Mandi(?",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mansoorah",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Marghzar Officers Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mason Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mateen Avenue",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Maulana Shaukat Ali Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "McLeod Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Medical Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mehar Fayaz Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Meharpura",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mehmood Booti",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mian Amiruddin Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mian Aziz Garden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mian Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mian Mir Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Military Accounts Housing",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Misri Shah",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Model Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Model Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mohafiz Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mohlanwal",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mohlanwal Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mominpur",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mozang",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mughalpura",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Multan Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Muslim Nagar Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Muslim Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mustafa Abad",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Mustafa Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Nadeem Shaheed Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Nasheman-e-Iqbal",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "National Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Nawab Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Nawaz Sharif Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Nayyab Villas",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Naz Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Nazir Garden Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Nespak Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "New Canal Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "New Chauburji Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "New Lahore City",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "New Muslim Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "New Super Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "NFC 1",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "NFC 2",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Nicholson Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Nisbat Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Nishat Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Nishtar Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Nizamabad",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Officer Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "OPF Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "P & D Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Pace Woodlands",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "PAF Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Pak Arab Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Pakki Thatti",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Paragon City",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Park View",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Park View Villas",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "PASSCO Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "PCSIR Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "PCSIR Staff Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Peco Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "PIA Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Poonch Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Prem Nagar",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Prime Home",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Punjab Coop Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Punjab Govt Employees Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Punjab Govt Servant Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Punjab Small Industries Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Punjab University Employees",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Qadri Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Qazi Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Qilla Gujjar Singh",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rail Town (Canal City)",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Railway Officers Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Raiwind Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Raj Garh",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rajpoot Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rana Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rang Mahal",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rasool Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ravi Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ravi Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Real Cottages",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rehan Garden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rehman City - Phase 4",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rehman Gardens",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rehman Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rehman Villas",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rehmanpura (Ferozpur Road)(?49) ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rehmanpura (Harbanspura)",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rehmat Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Revenue Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rifle Range Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Ring Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Riwaz Garden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rizwan Garden Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rohi Nala Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Royal Residencia",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Rustam Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sabzazar Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sadaat Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Saggian",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sahafi Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Saiden Shah Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Saidpur",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sajid Garden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Salamatpura",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Salli Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Samanabad",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Samanzar Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sami Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sanda",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sant Nagar",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Saroba Gardens Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shabbir Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shadab Garden",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shadbagh",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shadman 1",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shadman 2",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shah Faisal Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shah Jamal",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shah Kamal",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shahdara",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shahtaj Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shalimar Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shalimar Link Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shalimar Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sham Nagar",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sher Shah Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sheranwala Heights",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sheraz Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shershah Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sherwanee Town Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shiraz Villas",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Shoukat Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Siddiqia Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Singhpura",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sitara Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sodiwal",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Spring Meadows",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "State Life Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sue-e-Asal",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sufiabad",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sui Gas Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sukh Chayn Gardens",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sultan Pura",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sundar",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sundar Estate",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sunfort Gardens",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Sunny Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Super Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "T & T Aabpara Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Taj Bagh",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Tajpura",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Tariq Gardens",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "TECH Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Temple Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "The Spring Apartment Homes",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Thokar Niaz Baig",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Township",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Tricon Village",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "UBL Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "UET Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Umer Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "United Bank Officers",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Upper Mall",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Urdu Bazar",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Valencia Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Venus Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Vital Homes Housing Scheme",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Wafaqi Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Wahdat Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Wahdat Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Walled City",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Walton Railway Officers Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Walton Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Wapda Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Wapda Town",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Waris Road",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Wassanpura",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "West Wood Housing Society",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Wocland Villas",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Yasrab Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Youhanabad",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Zafar Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Zaheer Villas",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Zaman Colony",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Zaman Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> "Zubaida Park",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 1 ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 2 ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 3 ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 4 ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 5 ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 6 ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Town ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " Defence Raya ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " Defence Chowk ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " Main Boulevard  ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " Halloki Gardens  ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 1 Block A",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 1 Block B",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 1 Block C",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 1 Block D",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 1 Block E",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 1 Block F",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 1 Block G",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 1 Block J",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 1 Block K",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 1 Block L",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 1 Block M",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 1 Block N",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 1 Block P",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 1 Others",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 2 Block Q",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 2 Block R",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 2 Block S",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 2 Block T",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 2 Block U",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 2 Block V",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 2 Others",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 3 Block W",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 3 Block X",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 3 Block XX",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 3 Block Y",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 3 Block Z",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 3 Others",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 4 Block AA",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 4 Block BB",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 4 Block CC",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 4 Block DD",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 4 Block EE",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 4 Block FF",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 4 Block GG",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 4 Block HH",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 4 Block JJ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 4 Others",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 5 Block A",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 5 Block B",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 5 Block C",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 5 Block D",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 5 Block E",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 5 Block F",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 5 Block G",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 5 Block H",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 5 Block J",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 5 Block K",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 5 Block L",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 5 Block M",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 5 Others",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 6 Block A",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 6 Block B",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 6 Block C",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 6 Block D",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 6 Block E",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 6 Block F",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 6 Block G",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 6 Block H",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 6 Block J",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 6 Block K",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 6 Block L",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 6 Block M",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 6 Block N",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 6 Others",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block P",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block Q",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block R",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block S",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block T",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block U",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block V",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block W",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block X",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block Y",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block Z",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block Z1",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block Z2",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block CCA 1",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block CCA 3",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Block CCA 4",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 7 Others",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block A",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block B",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block C",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block D",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block E",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block F",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block G",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block H",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block J",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block L",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block M",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block N",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block P",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block Q",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block R",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block S",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block T",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block U",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block V",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block W",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block X",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block Y",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block Z",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block Z1",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block Z2",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block Z3",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block Z4",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block Z5",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Block Z6",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Commercial",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 CCA1",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 CCA2",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 8 Others",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Town Block A",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Town Block B",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Town Block C",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Town Block D",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Town Block E",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Town CCA",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Town Block Others",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Block A ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Block B ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Block C",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Block D ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Block E ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Block F ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Block G ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Block H ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Block J ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Block K ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Block L ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Block M ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Block N ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Block P ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Block Q ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Commercial Zone 1 ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Commercial Zone 2 ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Commercial Zone 3 ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Oval Commercial ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " DHA Phase 9 Prism Others ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " Halloki Gardens Block A ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " Halloki Gardens Block B ",'lat'=>0,'long'=>0],
        ['city_id'=>1, 'location'=> " Halloki Gardens Block Others ",'lat'=>0,'long'=>0],

        ]);
    }
}
